apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ratings-web
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: trigger-binding-ratings-web
      template:
        ref: trigger-template-ratings-web